AWS_ACCESS_KEY   = "AKIA4WW2WEOA4WX4GY55"
AWS_SECRET_KEY   = ""
AMI              = "ami-0a49b025fffbbdac6"
PRIVATE_KEY_PATH = "keys/ec2-key-pair.pem"
PUBLIC_KEY_PATH  = "keys/ec2-key-pair.pub"
EC2_USER         = "ec2-user"
